### ISSUE TITLE
Finished!

### ISSUE THREAD

**Issue by heraclex12** [heraclex12/Data-Science-Final-Project#1]
Hi,

Mình đã hoàn thành xong đồ án môn, hy vọng nhận được sự góp ý từ các bạn.

Hiếu.

**Comment by bason1999qn** [comment]
Chào bạn, mình có chút góp ý là bạn nên bổ sung phần tổng kết (nói về những thuận lợi, khó khăn và bài học rút ra) sau quá trình làm đồ án. Mong góp ý của mình có thể giúp bạn hoàn thiện đồ án 👍

**Comment by heraclex12** [comment]
Cảm ơn @bason1999qn đã góp ý.

Mình đã cập nhật thêm phần bạn nói tại commit này
https://github.com/heraclex12/Data-Science-Final-Project/commit/82a83502827d7654c9051cb73380d0944479a79f
